<?php
$entrants = [
	["name" => "Anchovies", "code" => "anchovy"],
	["name" => "Bacon", "code" => "bacon"],
	["name" => "Banana peppers", "code" => "banana_pepper"],
	["name" => "Barbecue sauce", "code" => "barbecue_sauce"],
	["name" => "Black olives", "code" => "black_olive"],
	["name" => "Chicken", "code" => "chicken"],
	["name" => "Extra cheese", "code" => "extra_cheese"],
	["name" => "Feta cheese", "code" => "feta_cheese"],
	["name" => "Garlic", "code" => "garlic"],
	["name" => "Green olives", "code" => "green_olive"],
	["name" => "Green peppers", "code" => "green_pepper"],
	["name" => "Ground beef", "code" => "ground_beef"],
	["name" => "Ham", "code" => "ham"],
	["name" => "Hot sauce", "code" => "hot_sauce"],
	["name" => "Jalapeno peppers", "code" => "jalapeno_pepper"],
	["name" => "Meatballs", "code" => "meatball"],
	["name" => "Mushrooms", "code" => "mushrooms"],
	["name" => "Onions", "code" => "onions"],
	["name" => "Pepperoni", "code" => "pepperoni"],
	["name" => "Pineapple", "code" => "pineapple"],
	["name" => "Salami", "code" => "salami"],
	["name" => "Sausage", "code" => "sausage"],
	["name" => "Spinach", "code" => "spinach"],
	["name" => "Steak", "code" => "steak"],
	["name" => "Tomato", "code" => "tomato"]
];

$maxvotes = 50;
$topic = "Which pizza topping is better?";
$haslinks = 0;
?>
